		g3log created log at: Thu Mar 02 11:37:54 2023
		LOG format: [YYYY/MM/DD hh:mm:ss uuu* LEVEL FILE->FUNCTION:LINE] messagen
		(uuu*: microseconds fractions of the seconds value)

2023/03/02 11:37:54 521033	INFO [python_manager.cpp->PythonManager::InitializePython:127]	Initializing Python ... 
2023/03/02 11:37:54 538909	INFO [python_manager.cpp->PythonManager::InitializePython:129]	Initializing Python DONE... 
2023/03/02 11:37:54 538917	INFO [python_manager.cpp->PythonManager::InitNumpy:172]	Init numpy... 
2023/03/02 11:37:54 643799	INFO [python_manager.cpp->PythonManager::InitNumpy:174]	Init numpy DONE... 
2023/03/02 11:38:22 760029	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/02 11:42:15 065640	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/02 11:44:02 402462	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/02 11:47:49 726562	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/02 11:50:56 046095	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/02 11:52:27 382194	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/02 12:00:22 000156	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/02 12:01:28 426029	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:/Users/user/OneDrive - ESTACA/Desktop/ESTAPARK2023/RTMapsYOLOv7\\BlocTrackingImage2Objets.py", line 188, in Core
    newObjet[0].kind = 0
', "TypeError: 'RealObject' object is not subscriptable
"]
2023/03/02 12:01:28 426456	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
