		g3log created log at: Wed Apr 26 16:52:41 2023
		LOG format: [YYYY/MM/DD hh:mm:ss uuu* LEVEL FILE->FUNCTION:LINE] messagen
		(uuu*: microseconds fractions of the seconds value)

2023/04/26 16:52:41 283259	INFO [python_manager.cpp->PythonManager::InitializePython:127]	Initializing Python ... 
2023/04/26 16:52:41 312484	INFO [python_manager.cpp->PythonManager::InitializePython:129]	Initializing Python DONE... 
2023/04/26 16:52:41 312492	INFO [python_manager.cpp->PythonManager::InitNumpy:172]	Init numpy... 
2023/04/26 16:52:41 477346	INFO [python_manager.cpp->PythonManager::InitNumpy:174]	Init numpy DONE... 
2023/04/26 16:53:19 486614	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 112, in Birth
    self.yolov7_detector = YOLOv7(model_path, conf_thres=0.5, iou_thres=0.5)
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\yolov7\\YOLOv7.py", line 17, in __init__
    self.initialize_model(path)
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\yolov7\\YOLOv7.py", line 23, in initialize_model
    self.session = onnxruntime.InferenceSession(path,
', '  File "C:\\Users\\ESTACA_TWIZY\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
', '  File "C:\\Users\\ESTACA_TWIZY\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
', "onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from models/yolov7-tiny_384x640.onnx failed:Load model models/yolov7-tiny_384x640.onnx failed. File doesn't exist
"]
2023/04/26 16:53:19 502478	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/04/26 16:54:51 186790	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 112, in Birth
    self.yolov7_detector = YOLOv7(model_path, conf_thres=0.5, iou_thres=0.5)
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\yolov7\\YOLOv7.py", line 17, in __init__
    self.initialize_model(path)
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\yolov7\\YOLOv7.py", line 23, in initialize_model
    self.session = onnxruntime.InferenceSession(path,
', '  File "C:\\Users\\ESTACA_TWIZY\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
', '  File "C:\\Users\\ESTACA_TWIZY\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
', "onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from models/yolov7-tiny_384x640.onnx failed:Load model models/yolov7-tiny_384x640.onnx failed. File doesn't exist
"]
2023/04/26 16:54:51 187098	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/04/26 16:55:19 201841	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 112, in Birth
    self.yolov7_detector = YOLOv7(model_path, conf_thres=0.5, iou_thres=0.5)
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\yolov7\\YOLOv7.py", line 17, in __init__
    self.initialize_model(path)
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\yolov7\\YOLOv7.py", line 23, in initialize_model
    self.session = onnxruntime.InferenceSession(path,
', '  File "C:\\Users\\ESTACA_TWIZY\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
', '  File "C:\\Users\\ESTACA_TWIZY\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
', "onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from models/yolov7-tiny_384x640.onnx failed:Load model models/yolov7-tiny_384x640.onnx failed. File doesn't exist
"]
2023/04/26 16:55:19 202207	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/04/26 17:07:15 418530	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 112, in Birth
    self.yolov7_detector = YOLOv7(model_path, conf_thres=0.5, iou_thres=0.5)
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\yolov7\\YOLOv7.py", line 17, in __init__
    self.initialize_model(path)
', '  File "C:/Users/ESTACA_TWIZY/Desktop/SEN-4/Main_Perception/PythonBridges\\yolov7\\YOLOv7.py", line 23, in initialize_model
    self.session = onnxruntime.InferenceSession(path,
', '  File "C:\\Users\\ESTACA_TWIZY\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
', '  File "C:\\Users\\ESTACA_TWIZY\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
', "onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from models/yolov7-tiny_384x640.onnx failed:Load model models/yolov7-tiny_384x640.onnx failed. File doesn't exist
"]
2023/04/26 17:07:15 418831	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/04/26 18:42:47 593931	INFO [python_manager.cpp->PythonManager::ProcessRTMapsAction:210]	Exiting now! All went well.
